jobs:
  include:
    - os: linux
      dist: bionic
      python: 3.7
      language: python
      services:
        - xvfb
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - os: osx
      osx_image: xcode11.3
      language: shell
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda info -a
  - conda env create -q --file requirements.yml
  - source activate atg
  - conda list

before_script:
  - cp ATGConfig.txt.template ATGConfig.txt
  - mkdir -p ~/ATGData/human/GRCh38
  - mkdir -p ~/ATGData/mouse/GRCm38
  - cp tests/data/hg38_chrom.sizes ~/ATGData/human/GRCh38/chrom.sizes
  - wget -O ~/ATGData/human/GRCh38/go_biological_process.csv http://homer.ucsd.edu/mchang/ATGData/human/Current/hg38/go_biological_process.csv
  - wget -O ~/ATGData/human/GRCh38/go_definition.csv http://homer.ucsd.edu/mchang/ATGData/human/Current/hg38/go_definition.csv
  - wget -O ~/ATGData/human/GRCh38/ensembl_gene.csv http://homer.ucsd.edu/mchang/ATGData/human/GRCh38/ensembl_gene.csv
  - wget -O ~/ATGData/mouse/GRCm38/ensembl_gene.csv http://homer.ucsd.edu/mchang/ATGData/mouse/GRCm38/ensembl_gene.csv

script: python -m pytest -k 'not retrieval'

