name: atg
channels:
- bioconda
- npdeloss
- conda-forge
- defaults
dependencies:
- python=3
- pysam
- bedtools
- pybedtools
- ucsc-bedgraphtobigwig
- pyyaml
- nose
- numpy
- pandas
- scipy
- matplotlib
- seaborn
- progress
- r::r-base
- rpy2
- bioconductor-deseq2
- bioconductor-gviz
- bioconductor-biomart
- meirlop
- pip
- pip:
    - pronto
